.TH WB "1" "January 2023" "GNU/UNIX AI HTML Generator" "AI HTML Generator"
.SH NAME
mkhtml \- generate html documents by the help of artificial intelligence
.SH SYNOPSIS
.B wb
[\fI\,OPTION\/\fR]... [\fI\,DATA\/\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
generate html documents with the mkhtml and openai text-davinci-003 together
.TP
\fB\-g [DATA]\fR, \fB\-\-generate [DATA]\fR
generate an html file with the help of openai text-davinci-003 
.TP
\fB\-k [DATA]\fR, \fB\-\-key [DATA]\fR
save the openai api key to the settings file
.TP
\fB\-c [CSS-DATA]\fR, \fB\-\-css [CSS-DATA]\fR
set the css for the html file
.TP
\fB\-s\fR, \fB\-\-settings\fR
output the settings configuration file
.TP
\fB\-h\fR, \fB\-\-help\fR
output a help menu
.TP
\fB\-v\fR, \fB\-\-version\fR
output the application version
.TP
\fB\-g\fR, \fB\-\-github\fR
output the github source code url
.SH "CSS-DATA (FILE STYLES)"
.PP
css-data adds a boilerplate design to the document
.TP
\fBempty\fR, no stylesheet\fR
.TP
\fBunix\fR, unix documentation stylesheet\fR
.TP
\fBcartoon\fR, cartoonish looking colorful stylesheet\fR
.TP
\fBelegant\fR, luxurious and modern looking stylesheet\fR
.TP
\fBwikipedia\fR, wikipedia stylesheet\fR
.TP
\fBfuture\fR, futuristic looking stylesheet\fR
.SH AUTHOR
Written by Mehmet Mert Gunduz.
.TP
.SH "REPORTING BUGS"
Open an issue: <https://github.com/MertGunduz/wb/issues/new/>
.SH COPYRIGHT
Copyright \(co 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
Full documentation <https://mertgunduz.github.io/wb/index.html>
.br